# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

clone:
  depth: full

  definitions:
    steps:
      - step: &build-test-sonarcloud
          name: Build, test and analyze on SonarCloud
          script:
            - echo '//registry.npmjs.org/:_authToken=0767a921-38e2-4b14-a305-d8a410261600' > .npmrc
            - npm install
            # need to check for db url
            - export MONGO_URL="mongodb+srv://cwrCGrdPqBI8RH9C:Z8qnnq7EPb2AvKnQ@cls-dev01-fabric-f6pv3.mongodb.net/pim_test?retryWrites=true&w=majority"
            - npm run test:coverage
            - pipe: sonarsource/sonarcloud-scan:1.0.1
      - step: &check-quality-gate-sonarcloud
          name: Check the Quality Gate on SonarCloud
          script:
            - pipe: sonarsource/sonarcloud-quality-gate:0.1.3
              variables:
                SONAR_TOKEN: ${SONAR_TOKEN}
      - step: &api-integration-test
          name: Test API's using newman and postman
          script:
            - npm install newman -g
            - export clientName=${CLIENT}
            - newman run https://www.getpostman.com/collections/29c060ce056c443c15d9 -e test/integration-tests/${clientName}/postman-integration-tests-dev.json
      - step: &auto-deploy
          name: AUTO_DEPLOY
          deployment: AUTO_DEPLOY
          caches:
            - node
          script:
            - echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > ~/.npmrc  && npm install
            - npm run build
            - npm version patch
            - npm publish
            - git clone -b ${DEPLOY_CONFIG_BRANCH} ${DEPLOY_CONFIG_REPO}
            - cd deployment-scripts
            - export STAGE=$AUTO_DEPLOY_STAGE
            - npm install && node deploy.js
      - step: &build-deploy-custom
          name: MANUAL_DEPLOY
          deployment: MANUAL_DEPLOY
          caches:
            - node
          script:
            - echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > ~/.npmrc  && npm install
            - git clone -b ${DEPLOY_CONFIG_BRANCH} ${DEPLOY_CONFIG_REPO}
            - cd deployment-scripts
            - npm install && node deploy.js
pipelines: # More info here: https://confluence.atlassian.com/bitbucket/configure-bitbucket-pipelines-yml-792298910.html
  branches:
    master:
      - step: *auto-deploy
  # pull-requests:
  #   '**':
  #     - step: *build-test-sonarcloud
  #     - step: *check-quality-gate-sonarcloud
      # - step: *api-integration-test # Developer need to add the right configs

  custom:
    manual-deploy:
      - variables:
        - name: CLIENT
        - name: STAGE
        - name: PLATFORM
        - name: SERVICE_NAME
      # - step: *build-test-sonarcloud   # Developer need to fix the tests and uncomment
      # - step: *check-quality-gate-sonarcloud #Developer need to fix the tests and uncomment
      - step: *build-deploy-custom
      # - step: *api-integration-test # Developer need to add the right configs
